{
    "bitwise": true,
    "camelcase": true,
    "curly": true,
    "eqeqeq": true,
    "es3": true,
    "forin": false,
    "immed": true,
    "indent": 4,
    "latedef": true,
    "maxdepth": 4,
    "maxstatements": 10,
    "maxlen": 80,
    "newcap": true,
    "noarg": true,
    "noempty": true,
    "nonew": true,
    "plusplus": true,
    "strict": true,
    "trailing": true,
    "undef": true,
    "unused": true
}
